### ISSUE TITLE
Linux Installation Instructions

### ISSUE THREAD

**Issue by CBqk3762** [aurora-multiphysics/cyclops#31]
I have been following the installation instructions for Linux, on a Debian build, and come across some problems.
`python3 -m venv venv` does not work on Debian/Ubuntu, the following error message appears:

```
cbyers@l2624:~/cyclops$ python3 -m venv venv
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.11-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: /home/cbyers/cyclops/venv/bin/python3
``` 
The suggested command `apt install python3.11-venv` does work **but** it is necessary to run the command in `venv/pyvenv.cfg` in order to produce` venv/bin/activate`, otherwise this does **not** exist.

Hopefully this is helpful!

**Comment by CBqk3762** [comment]
Additionally, `pip install -r requirements.txt` will not work, instead user should do `/path/to/venv/bin/pip install -r requirements.txt`

Possibly worth noting that this raises depreciation warnings for grapheme, future and pymoo when run.

**Comment by lukethehuman** [comment]
Thanks for finding this. Pull request #30 changes the installation and should resolve this.
